version: '3.8'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-initial-project
    volumes:
      - ./application:/app:rw
    ports:
      - "8000:8000"      
    # depends_on:
    #   - postgres
    networks: 
      - internal           

  postgres:
    image: postgres:latest
    container_name: postgres-nest-initial
    restart: always
    volumes:
      - ./sourcefiles/data:/var/lib/postgresql/data
      - ./sourcefiles/db/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: nestInit
      POSTGRES_PASSWORD: nestInit
      POSTGRES_DB: nestInit
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - "5432:5432"
    networks: 
      - internal 

networks:
  internal:
    driver: bridge       
       