version: '3.8'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-initial-project
    volumes:
      - ./application:/app:rw
    ports:
      - "3000:3000"      
    # depends_on:
    #   - postgres
    networks: 
      - internal           

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres-nest-initial
  #   restart: always
  #   environment:
  #     POSTGRES_ROOT_PASSWORD: root
  #     POSTGRES_USER: nest
  #     POSTGRES_PASSWORD: nest
  #     POSTGRES_DB: nest
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #     POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
  #   ports:
  #     - "5432:5432"
  #   networks: 
  #     - internal 

networks:
  internal:
    driver: bridge       
       